"""Render an iVisor sentry config file from a lowered Clay Seal envelope.

Policy knobs go in the file rather than the environment so the run leaves a
legible artifact that can be re-run by hand:

    ivisor --config <run_dir>/ivisor.conf run <elf>

Only iVisor's trace switches are passed as env (see driver.py).

FAIL-CLOSED ALLOWLIST VALIDATION: iVisor *warns and skips* an allowlist entry
it cannot parse, so a typo silently narrows egress toward deny-all rather than
failing. We validate every entry up front and raise instead — a policy that
does not mean what it says is a bug, not a degraded mode. Note the asymmetry is
only safe in this direction: a skipped entry can never widen access.
"""
from __future__ import annotations

import hashlib
import ipaddress
import re
from dataclasses import dataclass, field

# iVisor rejects unknown config keys with a hard error (crates/ivisor/src/
# config.rs). Emitting a key it does not know would abort the run, so the
# renderer is restricted to exactly the documented set.
KNOWN_KEYS = ("ram_mb", "rootfs", "workspace", "compute", "compute_ring_mb",
              "hostd", "allow", "listen", "sandbox")

# crates/ivisor/src/config.rs:145 — the fixed heap base plus a usable mmap
# arena needs >= 768 MiB, and the guest RAM size must be 16 MiB-granular.
MIN_RAM_MB = 768
RAM_GRANULARITY_MB = 16

_DOMAIN_CHARS = re.compile(r"^[A-Za-z0-9.-]+$")


class AllowEntryError(ValueError):
    """An egress allowlist entry iVisor would silently drop."""


def validate_allow_entry(entry: str) -> None:
    """Raise AllowEntryError unless `entry` is an IP or dotted domain, with an
    optional `:port`. Port of validate_allow in iVisor-demo's supervisor.rs.

    iVisor has no wildcard rules; `*.example.com` is not a narrower rule, it is
    a dropped one.
    """
    text = entry.strip()
    if not text:
        raise AllowEntryError("empty allowlist entry")
    host = text
    prefix, sep, tail = text.rpartition(":")
    if sep and tail.isdigit() and 0 <= int(tail) <= 65535:
        host = prefix
    host = host.strip("[]")
    if not host:
        raise AllowEntryError(f"allowlist entry {entry!r} has no host part")
    try:
        ipaddress.ip_address(host)
        return
    except ValueError:
        pass
    if "." not in host or not _DOMAIN_CHARS.match(host):
        raise AllowEntryError(
            f"allowlist entry {entry!r} is not an IP or a dotted domain name. "
            "iVisor has no wildcard rules, and it silently drops entries it "
            "cannot parse — which would leave egress more restricted than the "
            "policy claims.")


@dataclass(frozen=True)
class IVisorConfig:
    """One sentry configuration — the launch-time materialization of a grant."""

    rootfs: str
    workspace: str
    ram_mb: int = 1024
    allow: tuple[str, ...] = ()          # egress; empty means deny all
    listen: str | None = None            # ingress; None means deny all
    sandbox: bool = True                 # host-side Seatbelt profile
    comment: str = "generated by agentauth.capabilities.sandbox"
    extra: dict[str, str] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.ram_mb < MIN_RAM_MB or self.ram_mb % RAM_GRANULARITY_MB:
            raise ValueError(
                f"ram_mb = {self.ram_mb}: iVisor needs >= {MIN_RAM_MB} and "
                f"{RAM_GRANULARITY_MB} MiB-granular")
        for entry in self.allow:
            validate_allow_entry(entry)
        unknown = set(self.extra) - set(KNOWN_KEYS)
        if unknown:
            raise ValueError(
                f"unknown iVisor config key(s) {sorted(unknown)}; iVisor "
                "rejects these with a hard error")

    def render(self) -> str:
        """The config file text. Deterministic: the allowlist is sorted so the
        digest is stable across runs of the same grant."""
        lines = [f"# {self.comment}"]
        lines.append(f"ram_mb = {self.ram_mb}")
        lines.append(f"rootfs = {self.rootfs}")
        lines.append(f"workspace = {self.workspace}")
        lines.append(f"sandbox = {'on' if self.sandbox else 'off'}")
        if self.allow:
            lines.append("allow = " + ",".join(sorted(self.allow)))
        if self.listen:
            lines.append(f"listen = {self.listen}")
        for key in KNOWN_KEYS:
            if key in self.extra:
                lines.append(f"{key} = {self.extra[key]}")
        return "\n".join(lines) + "\n"

    def digest(self) -> str:
        """sha256 of the rendered text — the policy digest carried into
        attestation, binding every verdict to the exact policy that produced
        it. The comment line is excluded so a cosmetic label change does not
        look like a policy change."""
        body = "".join(line for line in self.render().splitlines(keepends=True)
                       if not line.startswith("#"))
        return hashlib.sha256(body.encode()).hexdigest()
