"""One sandboxed run, end to end: lower, stage, launch, attest.

This is the peer of the broker, not part of it. The caller authorizes an action
with ``SessionBroker.authorize`` and, on ALLOW, executes it here; the verdicts
that come back are evidence about that execution, not a second authorization
request. Keeping them apart matters concretely: one tool call produces hundreds
of syscalls, so feeding them back through ``authorize`` would double-count the
trajectory and let the substrate's own noise drive behavioral scores.

Each run leaves a self-contained artifact:

    <run_root>/<run_id>/
      ivisor.conf     # the exact policy, re-runnable by hand
      workspace/      # what the guest could see
      trace.jsonl     # every verified verdict
      result.json     # exit interpretation, summaries, digests

so an incident review can replay the run without reconstructing anything.
"""
from __future__ import annotations

import json
import uuid
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path

from agentauth.capabilities.sandbox.attest import (
    log_sandbox_run,
    sandboxing_context,
)
from agentauth.capabilities.sandbox.driver import IVisorResult, run_ivisor
from agentauth.capabilities.sandbox.lowering import LoweredPolicy, lower_to_ivisor
from agentauth.capabilities.sandbox.monitor_feed import actions_from_events
from agentauth.capabilities.sandbox.staging import (
    StagedWorkspace,
    stage_workspace,
    workspace_delta,
)
from agentauth.capabilities.sandbox.verdicts import PolicyEvent

DEFAULT_TIMEOUT_S = 120.0


@dataclass
class SandboxRunSpec:
    """Everything one sandboxed run needs."""

    elf: str
    guest_args: tuple[str, ...] = ()
    rootfs: str = ""
    run_root: Path = field(default_factory=lambda: Path(".sandbox-runs"))
    ivisor_bin: str = "ivisor"

    # The envelope. Only egress and paths lower; see lowering.py.
    egress: object | None = None
    scope: object | None = None
    lease: object | None = None
    repo_root: Path | str | None = None

    ram_mb: int = 1024
    timeout_s: float | None = DEFAULT_TIMEOUT_S
    extra_allow: tuple[str, ...] = ()
    extra_files: Mapping[str, Path | str] = field(default_factory=dict)
    listen: str | None = None
    sandbox: bool = True
    workspace_mode: str = "stage"
    trace: Sequence[str] = ("policy",)

    # Reuse a previous run's directory so episode state persists across the
    # per-call spawns an agent loop makes.
    reuse_run_dir: Path | None = None
    run_id: str | None = None
    query_id: str | None = None
    # Which tool this run is charged to, for the compute-seconds ledger.
    tool_name: str = "sandbox.run"


@dataclass
class SandboxOutcome:
    run_id: str
    result: IVisorResult
    lowered: LoweredPolicy
    staged: StagedWorkspace
    actions: tuple = ()
    sandboxing: dict = field(default_factory=dict)
    delta: dict = field(default_factory=dict)

    @property
    def denied(self) -> tuple[PolicyEvent, ...]:
        return self.result.denials()

    @property
    def evidence_ok(self) -> bool:
        return self.result.evidence_ok


def run_sandboxed(spec: SandboxRunSpec, *,
                  receipt_sink: Callable[[dict], None] | None = None,
                  decision_log=None,
                  compute_budget=None,
                  on_event: Callable[[PolicyEvent], None] | None = None,
                  ) -> SandboxOutcome:
    """Lower the envelope, stage the workspace, run the guest, attest the result."""
    run_id = spec.run_id or uuid.uuid4().hex[:12]
    run_dir = (Path(spec.reuse_run_dir) if spec.reuse_run_dir
               else Path(spec.run_root) / run_id)
    workspace = run_dir / "workspace"

    lowered = lower_to_ivisor(
        rootfs=spec.rootfs, workspace=workspace, egress=spec.egress,
        scope=spec.scope, lease=spec.lease, repo_root=spec.repo_root,
        ram_mb=spec.ram_mb, extra_allow=spec.extra_allow,
        extra_files=spec.extra_files, listen=spec.listen, sandbox=spec.sandbox,
        workspace_mode=spec.workspace_mode,
        comment=f"generated by agentauth.capabilities.sandbox for run {run_id}")

    staged = stage_workspace(lowered.staging, spec.run_root, run_id=run_id,
                             reuse=run_dir)
    run_dir.mkdir(parents=True, exist_ok=True)
    config_path = run_dir / "ivisor.conf"
    config_path.write_text(lowered.config.render())

    # The reservation IS the kill timer: whatever the grant has left becomes the
    # timeout, so a compute ceiling is enforced rather than merely recorded.
    timeout_s = spec.timeout_s
    reservation = None
    if compute_budget is not None:
        reservation = compute_budget.reserve(
            spec.tool_name, timeout_s if timeout_s is not None else 0.0)
        if not reservation.allowed:
            raise ComputeBudgetExhausted(
                f"compute budget refused this run: {reservation.reason}")
        if timeout_s is not None:
            timeout_s = min(timeout_s, reservation.granted_seconds)

    try:
        result = run_ivisor(
            ivisor_bin=spec.ivisor_bin, config_path=config_path, elf=spec.elf,
            guest_args=spec.guest_args, trace=spec.trace, timeout_s=timeout_s,
            on_event=on_event)
    except BaseException:
        if reservation is not None:
            reservation.release()
        raise
    if reservation is not None:
        reservation.commit(result.wall_seconds)

    delta = workspace_delta(staged)
    payload = sandboxing_context(
        result=result, lowered=lowered, staged=staged, run_id=run_id,
        ivisor_bin=spec.ivisor_bin, config_path=config_path,
        workspace_delta=delta)

    _write_artifacts(run_dir, result, payload)
    log_sandbox_run(payload, decision_log=decision_log, query_id=spec.query_id,
                    receipt_sink=receipt_sink)

    return SandboxOutcome(
        run_id=run_id, result=result, lowered=lowered, staged=staged,
        actions=tuple(actions_from_events(result.events)),
        sandboxing=payload, delta=delta)


class ComputeBudgetExhausted(RuntimeError):
    """The compute-seconds grant had nothing left for this run."""


def _write_artifacts(run_dir: Path, result: IVisorResult,
                     payload: dict) -> None:
    with open(run_dir / "trace.jsonl", "w") as handle:
        for event in result.events:      # verified only, by construction
            handle.write(json.dumps({
                "event": event.event, "verdict": event.verdict.value,
                "fields": dict(event.fields), "at_ms": event.at_ms}) + "\n")
    (run_dir / "result.json").write_text(json.dumps(payload, indent=2,
                                                    sort_keys=True))
